apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movies-api
  namespace: movies
  labels:
    app.kubernetes.io/name: movies-api
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movies-api
                port:
                  number: 8080
